radix define operation {
  0 "OP_LUI"
  1 "OP_AUIPC"
  2 "OP_ADDI"
  3 "OP_SLTI"
  4 "OP_SLTIU"
  5 "OP_XORI"
  6 "OP_ORI"
  7 "OP_ANDI"
  8 "OP_SLLI"
  9 "OP_SRLI"
  10 "OP_SRAI"
  11 "OP_ADD"
  12 "OP_SUB"
  13 "OP_SLL"
  14 "OP_SLT"
  15 "OP_SLTU"
  16 "OP_XOR"
  17 "OP_SRL"
  18 "OP_SRA"
  19 "OP_OR"
  20 "OP_AND"
  21 "OP_FENCE"
  22 "OP_ECALL"
  23 "OP_EBREAK"
  24 "OP_LB"
  25 "OP_LH"
  26 "OP_LW"
  27 "OP_LBU"
  28 "OP_LHU"
  29 "OP_SB"
  30 "OP_SH"
  31 "OP_SW"
  32 "OP_JAL"
  33 "OP_JALR"
  34 "OP_BEQ"
  35 "OP_BNE"
  36 "OP_BLT"
  37 "OP_BGE"
  38 "OP_BLTU"
  39 "OP_BGEU"
  40 "OP_ILLEGAL"
}

radix define processor_state {
  0 "START_FETCH"
  1 "FETCH"
  2 "START_MEM"
  3 "MEM_ACCESS"
  4 "WRITEBACK"
}