onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix hexadecimal /riscv/CLOCK_50
add wave -noupdate -radix hexadecimal /riscv/FL_ADDR
add wave -noupdate -radix hexadecimal /riscv/FL_DQ
add wave -noupdate -radix hexadecimal /riscv/FL_OE_N
add wave -noupdate -radix hexadecimal /riscv/FL_RST_N
add wave -noupdate -radix hexadecimal /riscv/FL_WE_N
add wave -noupdate -radix hexadecimal /riscv/SRAM_ADDR
add wave -noupdate -radix hexadecimal /riscv/SRAM_DQ
add wave -noupdate -radix hexadecimal /riscv/SRAM_WE_N
add wave -noupdate -radix hexadecimal /riscv/SRAM_OE_N
add wave -noupdate -radix hexadecimal /riscv/SRAM_UB_N
add wave -noupdate -radix hexadecimal /riscv/SRAM_LB_N
add wave -noupdate -radix hexadecimal /riscv/SRAM_CE_N
add wave -noupdate -radix hexadecimal /riscv/SW
add wave -noupdate -radix hexadecimal /riscv/KEY
add wave -noupdate -radix hexadecimal /riscv/LEDR
add wave -noupdate -radix hexadecimal /riscv/LEDG
add wave -noupdate -radix hexadecimal /riscv/HEX0
add wave -noupdate -radix hexadecimal /riscv/HEX1
add wave -noupdate -radix hexadecimal /riscv/HEX2
add wave -noupdate -radix hexadecimal /riscv/HEX3
add wave -noupdate -radix hexadecimal /riscv/VGA_R
add wave -noupdate -radix hexadecimal /riscv/VGA_G
add wave -noupdate -radix hexadecimal /riscv/VGA_B
add wave -noupdate -radix hexadecimal /riscv/VGA_HS
add wave -noupdate -radix hexadecimal /riscv/VGA_VS
add wave -noupdate -radix hexadecimal /riscv/PS2_CLK
add wave -noupdate -radix hexadecimal /riscv/PS2_DAT
add wave -noupdate -radix hexadecimal /riscv/TEST_ALLOW_WB_COMPLETE
add wave -noupdate -radix hexadecimal /riscv/TEST_REG_IN
add wave -noupdate -radix hexadecimal /riscv/TEST_REG_OUT
add wave -noupdate -radix hexadecimal /riscv/rst_n
add wave -noupdate -radix hexadecimal /riscv/processor_state
add wave -noupdate -radix hexadecimal /riscv/processor_privilege
add wave -noupdate -radix hexadecimal /riscv/next_privilege
add wave -noupdate -radix hexadecimal /riscv/decoder_op
add wave -noupdate -radix hexadecimal /riscv/mem_mux_finished
add wave -noupdate -radix hexadecimal /riscv/memory_write_request
add wave -noupdate -radix hexadecimal /riscv/memory_read_request
add wave -noupdate -radix hexadecimal /riscv/memory_byte_mode
add wave -noupdate -radix hexadecimal /riscv/memory_addr
add wave -noupdate -radix hexadecimal /riscv/memory_data_in
add wave -noupdate -radix hexadecimal /riscv/memory_data_out
add wave -noupdate -radix hexadecimal /riscv/memory_busy
add wave -noupdate -radix hexadecimal /riscv/memory_finished
add wave -noupdate -radix hexadecimal /riscv/vga_pen_x
add wave -noupdate -radix hexadecimal /riscv/vga_pen_y
add wave -noupdate -radix hexadecimal /riscv/vga_pen_color
add wave -noupdate -radix hexadecimal /riscv/vga_pen_draw
add wave -noupdate -radix hexadecimal /riscv/ps2_get_key
add wave -noupdate -radix hexadecimal /riscv/ps2_key_pressed
add wave -noupdate -radix hexadecimal /riscv/fetch_read_request
add wave -noupdate -radix hexadecimal /riscv/fetch_addr
add wave -noupdate -radix hexadecimal /riscv/fetch_result
add wave -noupdate -radix hexadecimal /riscv/mem_access_read_request
add wave -noupdate -radix hexadecimal /riscv/mem_access_write_request
add wave -noupdate -radix hexadecimal /riscv/mem_access_addr
add wave -noupdate -radix hexadecimal /riscv/mem_access_data_in
add wave -noupdate -radix hexadecimal /riscv/mem_access_byte_mode
add wave -noupdate -radix hexadecimal /riscv/mem_access_data_out
add wave -noupdate -radix hexadecimal /riscv/rs1_bank_interface_in
add wave -noupdate -radix hexadecimal /riscv/rs2_bank_interface_in
add wave -noupdate -radix hexadecimal /riscv/rs1_bank_interface_out
add wave -noupdate -radix hexadecimal /riscv/rs2_bank_interface_out
add wave -noupdate -radix hexadecimal /riscv/rd_writeback_reg
add wave -noupdate -radix hexadecimal /riscv/rd_writeback_val
add wave -noupdate -radix hexadecimal /riscv/next_pc
add wave -noupdate -radix hexadecimal /riscv/pc
add wave -noupdate -radix hexadecimal /riscv/instruction32
add wave -noupdate -radix hexadecimal /riscv/decoder_rd
add wave -noupdate -radix hexadecimal /riscv/decoder_rs1
add wave -noupdate -radix hexadecimal /riscv/decoder_rs2
add wave -noupdate -radix hexadecimal /riscv/decoder_imm
add wave -noupdate -radix hexadecimal /riscv/decoder_csr_i
add wave -noupdate -radix hexadecimal /riscv/csr_read
add wave -noupdate -radix hexadecimal /riscv/illegal_csr_access
add wave -noupdate -radix hexadecimal /riscv/timer_irq
add wave -noupdate -radix hexadecimal /riscv/external_irq
add wave -noupdate -radix hexadecimal /riscv/mstatus
add wave -noupdate -radix hexadecimal /riscv/mtvec
add wave -noupdate -radix hexadecimal /riscv/mcause
add wave -noupdate -radix hexadecimal /riscv/mtval
add wave -noupdate -radix hexadecimal /riscv/mepc
add wave -noupdate -radix hexadecimal /riscv/mie
add wave -noupdate -radix hexadecimal /riscv/mip
add wave -noupdate -radix hexadecimal /riscv/mscratch
add wave -noupdate -radix hexadecimal /riscv/next_mstatus
add wave -noupdate -radix hexadecimal /riscv/next_mtvec
add wave -noupdate -radix hexadecimal /riscv/next_mcause
add wave -noupdate -radix hexadecimal /riscv/next_mtval
add wave -noupdate -radix hexadecimal /riscv/next_mepc
add wave -noupdate -radix hexadecimal /riscv/TEST_PROBE_NEW_CSR_VAL
add wave -noupdate -radix hexadecimal /riscv/execute_next_pc
add wave -noupdate -radix hexadecimal /riscv/execute_result
add wave -noupdate -radix hexadecimal /riscv/memory_access_result
add wave -noupdate -radix hexadecimal /riscv/hex_num
add wave -noupdate -radix hexadecimal /riscv/hex_upp_sel
add wave -noupdate -radix hexadecimal /riscv/step
add wave -noupdate -divider mem
add wave -noupdate -radix hexadecimal /riscv/mem/clk
add wave -noupdate -radix hexadecimal /riscv/mem/rst_n
add wave -noupdate -radix hexadecimal /riscv/mem/write_request
add wave -noupdate -radix hexadecimal /riscv/mem/read_request
add wave -noupdate -radix hexadecimal /riscv/mem/byte_mode
add wave -noupdate -radix hexadecimal /riscv/mem/addr_in
add wave -noupdate -radix hexadecimal /riscv/mem/data_in
add wave -noupdate -radix hexadecimal /riscv/mem/data_out
add wave -noupdate -radix hexadecimal /riscv/mem/busy
add wave -noupdate -radix hexadecimal /riscv/mem/finished
add wave -noupdate -radix hexadecimal /riscv/mem/FL_ADDR
add wave -noupdate -radix hexadecimal /riscv/mem/FL_DQ
add wave -noupdate -radix hexadecimal /riscv/mem/FL_OE_N
add wave -noupdate -radix hexadecimal /riscv/mem/FL_RST_N
add wave -noupdate -radix hexadecimal /riscv/mem/FL_WE_N
add wave -noupdate -radix hexadecimal /riscv/mem/SRAM_ADDR
add wave -noupdate -radix hexadecimal /riscv/mem/SRAM_DQ
add wave -noupdate -radix hexadecimal /riscv/mem/SRAM_WE_N
add wave -noupdate -radix hexadecimal /riscv/mem/SRAM_OE_N
add wave -noupdate -radix hexadecimal /riscv/mem/SRAM_UB_N
add wave -noupdate -radix hexadecimal /riscv/mem/SRAM_LB_N
add wave -noupdate -radix hexadecimal /riscv/mem/SRAM_CE_N
add wave -noupdate -radix hexadecimal /riscv/mem/LEDR
add wave -noupdate -radix hexadecimal /riscv/mem/vga_pen_x
add wave -noupdate -radix hexadecimal /riscv/mem/vga_pen_y
add wave -noupdate -radix hexadecimal /riscv/mem/vga_pen_color
add wave -noupdate -radix hexadecimal /riscv/mem/vga_pen_draw
add wave -noupdate -radix hexadecimal /riscv/mem/ps2_get_key
add wave -noupdate -radix hexadecimal /riscv/mem/ps2_key_pressed
add wave -noupdate -radix hexadecimal /riscv/mem/flash_read_request
add wave -noupdate -radix hexadecimal /riscv/mem/flash_addr
add wave -noupdate -radix hexadecimal /riscv/mem/flash_data
add wave -noupdate -radix hexadecimal /riscv/mem/flash_finished
add wave -noupdate -radix hexadecimal /riscv/mem/flash_busy
add wave -noupdate -radix hexadecimal /riscv/mem/flash_byte_mode
add wave -noupdate -radix hexadecimal /riscv/mem/sram_read_request
add wave -noupdate -radix hexadecimal /riscv/mem/sram_write_request
add wave -noupdate -radix hexadecimal /riscv/mem/sram_addr
add wave -noupdate -radix hexadecimal /riscv/mem/sram_data_in
add wave -noupdate -radix hexadecimal /riscv/mem/sram_data_out
add wave -noupdate -radix hexadecimal /riscv/mem/sram_finished
add wave -noupdate -radix hexadecimal /riscv/mem/sram_busy
add wave -noupdate -radix hexadecimal /riscv/mem/sram_byte_mode
add wave -noupdate -radix hexadecimal /riscv/mem/mapped_read_request
add wave -noupdate -radix hexadecimal /riscv/mem/mapped_write_request
add wave -noupdate -radix hexadecimal /riscv/mem/mapped_addr
add wave -noupdate -radix hexadecimal /riscv/mem/mapped_data_in
add wave -noupdate -radix hexadecimal /riscv/mem/mapped_data_out
add wave -noupdate -radix hexadecimal /riscv/mem/mapped_finished
add wave -noupdate -radix hexadecimal /riscv/mem/mapped_busy
add wave -noupdate -radix hexadecimal /riscv/mem/last_module
add wave -noupdate -radix hexadecimal /riscv/mem/next_module
add wave -noupdate -divider processor_state
add wave -noupdate -radix hexadecimal /riscv/processor_state_manager/clk
add wave -noupdate -radix hexadecimal /riscv/processor_state_manager/rst_n
add wave -noupdate -radix hexadecimal /riscv/processor_state_manager/mem_finished
add wave -noupdate -radix hexadecimal /riscv/processor_state_manager/decoder_op
add wave -noupdate -radix hexadecimal /riscv/processor_state_manager/next_privilege
add wave -noupdate -radix hexadecimal /riscv/processor_state_manager/processor_state
add wave -noupdate -radix hexadecimal /riscv/processor_state_manager/processor_privilege
add wave -noupdate -radix hexadecimal /riscv/processor_state_manager/TEST_ALLOW_WB_COMPLETE
add wave -noupdate -radix hexadecimal /riscv/processor_state_manager/next_state
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/rst_n
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/processor_state
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/fetch_read_request
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/fetch_addr
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/fetch_result
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/mem_access_read_request
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/mem_access_write_request
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/mem_access_addr
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/mem_access_data_in
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/mem_access_byte_mode
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/mem_access_data_out
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/finished
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/memory_read_request
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/memory_write_request
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/memory_byte_mode
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/memory_addr
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/memory_data_in
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/memory_data_out
add wave -noupdate -radix hexadecimal /riscv/memory_multiplexer/memory_finished
add wave -noupdate -radix hexadecimal /riscv/instruction_fetch_and_pc/clk
add wave -noupdate -radix hexadecimal /riscv/instruction_fetch_and_pc/rst_n
add wave -noupdate -radix hexadecimal /riscv/instruction_fetch_and_pc/processor_state
add wave -noupdate -radix hexadecimal /riscv/instruction_fetch_and_pc/next_pc
add wave -noupdate -radix hexadecimal /riscv/instruction_fetch_and_pc/pc
add wave -noupdate -radix hexadecimal /riscv/instruction_fetch_and_pc/instruction32
add wave -noupdate -radix hexadecimal /riscv/instruction_fetch_and_pc/mem_read_request
add wave -noupdate -radix hexadecimal /riscv/instruction_fetch_and_pc/mem_addr
add wave -noupdate -radix hexadecimal /riscv/instruction_fetch_and_pc/mem_read_result
add wave -noupdate -radix hexadecimal /riscv/instruction_fetch_and_pc/mem_finished
add wave -noupdate -radix hexadecimal /riscv/instruction_fetch_and_pc/TEST_ALLOW_WB_COMPLETE
add wave -noupdate -radix hexadecimal /riscv/instruction_fetch_and_pc/saved_instruction32
add wave -noupdate -radix hexadecimal /riscv/decoder/rst_n
add wave -noupdate -radix hexadecimal /riscv/decoder/instruction32
add wave -noupdate -radix hexadecimal /riscv/decoder/op
add wave -noupdate -radix hexadecimal /riscv/decoder/rd
add wave -noupdate -radix hexadecimal /riscv/decoder/rs1
add wave -noupdate -radix hexadecimal /riscv/decoder/rs2
add wave -noupdate -radix hexadecimal /riscv/decoder/imm
add wave -noupdate -radix hexadecimal /riscv/decoder/csr_i
add wave -noupdate -radix hexadecimal /riscv/decoder/rs1_bank_interface_in
add wave -noupdate -radix hexadecimal /riscv/decoder/rs2_bank_interface_in
add wave -noupdate -radix hexadecimal /riscv/decoder/rs1_bank_interface_out
add wave -noupdate -radix hexadecimal /riscv/decoder/rs2_bank_interface_out
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/clk
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/rst_n
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/processor_state
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/processor_privilege
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/TEST_ALLOW_WB_COMPLETE
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/external_irq
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/timer_irq
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/op
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/imm
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/rs1_val
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/csr_i
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/csr_read
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/mstatus
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/mtvec
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/mcause
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/mtval
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/mepc
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/mie
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/mip
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/mscratch
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/next_mstatus
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/next_mtvec
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/next_mcause
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/next_mtval
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/next_mepc
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/illegal_csr_access
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/TEST_PROBE_NEW_CSR_VAL
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/required_priv
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/instruction_is_csr_op
add wave -noupdate -radix hexadecimal /riscv/control_status_registers/new_csr_value
add wave -noupdate -radix hexadecimal /riscv/trap_manager/clk
add wave -noupdate -radix hexadecimal /riscv/trap_manager/rst_n
add wave -noupdate -radix hexadecimal /riscv/trap_manager/pc
add wave -noupdate -radix hexadecimal /riscv/trap_manager/execute_next_pc
add wave -noupdate -radix hexadecimal /riscv/trap_manager/next_pc
add wave -noupdate -radix hexadecimal /riscv/trap_manager/op
add wave -noupdate -radix hexadecimal /riscv/trap_manager/illegal_csr_access
add wave -noupdate -radix hexadecimal /riscv/trap_manager/processor_state
add wave -noupdate -radix hexadecimal /riscv/trap_manager/processor_privilege
add wave -noupdate -radix hexadecimal /riscv/trap_manager/next_privilege
add wave -noupdate -radix hexadecimal /riscv/trap_manager/mstatus
add wave -noupdate -radix hexadecimal /riscv/trap_manager/mtvec
add wave -noupdate -radix hexadecimal /riscv/trap_manager/mcause
add wave -noupdate -radix hexadecimal /riscv/trap_manager/mtval
add wave -noupdate -radix hexadecimal /riscv/trap_manager/mepc
add wave -noupdate -radix hexadecimal /riscv/trap_manager/mip
add wave -noupdate -radix hexadecimal /riscv/trap_manager/mie
add wave -noupdate -radix hexadecimal /riscv/trap_manager/next_mstatus
add wave -noupdate -radix hexadecimal /riscv/trap_manager/next_mtvec
add wave -noupdate -radix hexadecimal /riscv/trap_manager/next_mcause
add wave -noupdate -radix hexadecimal /riscv/trap_manager/next_mtval
add wave -noupdate -radix hexadecimal /riscv/trap_manager/next_mepc
add wave -noupdate -radix hexadecimal /riscv/trap_manager/ecall
add wave -noupdate -radix hexadecimal /riscv/trap_manager/ebreak
add wave -noupdate -radix hexadecimal /riscv/trap_manager/mret
add wave -noupdate -radix hexadecimal /riscv/trap_manager/external_irq
add wave -noupdate -radix hexadecimal /riscv/trap_manager/timer_irq
add wave -noupdate -radix hexadecimal /riscv/execute/rst_n
add wave -noupdate -radix hexadecimal /riscv/execute/op
add wave -noupdate -radix hexadecimal /riscv/execute/rd
add wave -noupdate -radix hexadecimal /riscv/execute/rs1
add wave -noupdate -radix hexadecimal /riscv/execute/rs2
add wave -noupdate -radix hexadecimal /riscv/execute/imm
add wave -noupdate -radix hexadecimal /riscv/execute/pc
add wave -noupdate -radix hexadecimal /riscv/execute/csr_read
add wave -noupdate -radix hexadecimal /riscv/execute/res
add wave -noupdate -radix hexadecimal /riscv/execute/next_pc
add wave -noupdate -radix hexadecimal /riscv/execute/rs1_s
add wave -noupdate -radix hexadecimal /riscv/execute/rs2_s
add wave -noupdate -radix hexadecimal /riscv/execute/imm_s
add wave -noupdate -radix hexadecimal /riscv/memory_access/clk
add wave -noupdate -radix hexadecimal /riscv/memory_access/rst_n
add wave -noupdate -radix hexadecimal /riscv/memory_access/processor_state
add wave -noupdate -radix hexadecimal /riscv/memory_access/op
add wave -noupdate -radix hexadecimal /riscv/memory_access/write_data
add wave -noupdate -radix hexadecimal /riscv/memory_access/execute_result
add wave -noupdate -radix hexadecimal /riscv/memory_access/read_res
add wave -noupdate -radix hexadecimal /riscv/memory_access/mem_access_read_request
add wave -noupdate -radix hexadecimal /riscv/memory_access/mem_access_write_request
add wave -noupdate -radix hexadecimal /riscv/memory_access/mem_access_addr
add wave -noupdate -radix hexadecimal /riscv/memory_access/mem_access_data
add wave -noupdate -radix hexadecimal /riscv/memory_access/mem_access_byte_mode
add wave -noupdate -radix hexadecimal /riscv/memory_access/mem_access_result
add wave -noupdate -radix hexadecimal /riscv/memory_access/mem_access_finished
add wave -noupdate -radix hexadecimal /riscv/memory_access/mem_access_busy
add wave -noupdate -radix hexadecimal /riscv/reg_writeback/clk
add wave -noupdate -radix hexadecimal /riscv/reg_writeback/rst_n
add wave -noupdate -radix hexadecimal /riscv/reg_writeback/processor_state
add wave -noupdate -radix hexadecimal /riscv/reg_writeback/rd_in
add wave -noupdate -radix hexadecimal /riscv/reg_writeback/op
add wave -noupdate -radix hexadecimal /riscv/reg_writeback/execute_result
add wave -noupdate -radix hexadecimal /riscv/reg_writeback/mem_out
add wave -noupdate -radix hexadecimal /riscv/reg_writeback/reg_bank_rd
add wave -noupdate -radix hexadecimal /riscv/reg_writeback/reg_bank_val
add wave -noupdate -radix hexadecimal /riscv/mem/flash32/clk
add wave -noupdate -radix hexadecimal /riscv/mem/flash32/rst_n
add wave -noupdate -radix hexadecimal /riscv/mem/flash32/interface_addr
add wave -noupdate -radix hexadecimal /riscv/mem/flash32/interface_data
add wave -noupdate -radix hexadecimal /riscv/mem/flash32/byte_mode
add wave -noupdate -radix hexadecimal /riscv/mem/flash32/read_request
add wave -noupdate -radix hexadecimal /riscv/mem/flash32/addr
add wave -noupdate -radix hexadecimal /riscv/mem/flash32/data
add wave -noupdate -radix hexadecimal /riscv/mem/flash32/finished
add wave -noupdate -radix hexadecimal /riscv/mem/flash32/busy
add wave -noupdate -radix hexadecimal /riscv/mem/flash32/state
add wave -noupdate -radix hexadecimal /riscv/mem/flash32/next_state
add wave -noupdate -radix hexadecimal /riscv/mem/flash32/delay_counter
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/clk
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/rst_n
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/interface_addr
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/interface_data
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/interface_upper_byte_mask_n
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/interface_lower_byte_mask_n
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/interface_output_enable_n
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/interface_write_enable_n
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/byte_mode
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/read_request
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/addr
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/write_request
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/write_data
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/data_out
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/finished
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/busy
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/TEST_EXPOSE_STATE
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/writing
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/write_halfword
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/state
add wave -noupdate -radix hexadecimal /riscv/mem/sram32/next_state
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/clk
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/rst_n
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/read_request
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/write_request
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/addr
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/data_in
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/data_out
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/finished
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/busy
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/LEDR
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/vga_pen_x
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/vga_pen_y
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/vga_pen_color
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/vga_pen_draw
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/ps2_get_key
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/ps2_key_pressed
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/state
add wave -noupdate -radix hexadecimal /riscv/mem/memory_mapped_io/next_state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {138 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 333
configure wave -valuecolwidth 102
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {848 ps}
